import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { detectDeviceServer } from "@/features/device-detector/device-detector.server";
import { DeviceProvider } from "@/features/device-detector/device-provider";
import { instrumentSans, instrumentSerifRough } from "./fonts/instrument-sans";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initial = await detectDeviceServer(); 
  return (
    <html lang="en">
      <body className={`${instrumentSans.variable} ${instrumentSerifRough.variable}`}>
        <DeviceProvider initial={initial}>
          {children} 
        </DeviceProvider>
      </body>
    </html>
  );
}
